from __future__ import annotations

import argparse
import html
import os
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Sequence
from pathlib import Path
from urllib.parse import urlsplit


SERVER_ENV_VAR = "MACROSIGNAGE_SERVER_URL"
TOKEN_ENV_VAR = "MACROSIGNAGE_DISPLAY_TOKEN"
FIREFOX_ENV_VAR = "MACROSIGNAGE_FIREFOX"


def normalize_server(value: str) -> str:
    server = value.strip()
    if "://" not in server:
        server = f"http://{server}"
    parsed = urlsplit(server)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError(f"Invalid server URL: {value!r}")
    return server.rstrip("/")


def find_firefox(explicit: str | None) -> str:
    candidate = explicit or os.environ.get(FIREFOX_ENV_VAR) or "firefox"
    resolved = shutil.which(candidate)
    if not resolved:
        raise RuntimeError(
            f"Firefox binary {candidate!r} not found. Set {FIREFOX_ENV_VAR} or pass --firefox."
        )
    return resolved


USER_JS = """\
// Generated by macrosignage-kiosk. Loosens privacy defaults so the session
// cookie set by /displays/<id>/pair survives the file:// -> http:// redirect.
// This profile is dedicated to a single display; broader browsing is not
// intended.
user_pref("network.cookie.cookieBehavior", 0);
user_pref("privacy.firstparty.isolate", false);
user_pref("privacy.partition.network_state", false);
user_pref("privacy.trackingprotection.enabled", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("startup.homepage_welcome_url", "");
user_pref("startup.homepage_welcome_url.additional", "");
user_pref("datareporting.policy.firstRunURL", "");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
"""


def render_pair_page(server: str, display_id: int, token: str) -> str:
    """Tiny self-submitting form that posts the token to /displays/<id>/pair.

    The server responds 302 → /displays/<id>/play and sets the session cookie,
    so Firefox handles cookie persistence natively (no schema injection).
    """
    action = f"{server}/displays/{display_id}/pair"
    return (
        "<!doctype html><html><head><meta charset=\"utf-8\">"
        f"<title>MacroSignage display {display_id}</title>"
        "<style>html,body{background:#000;color:#888;font-family:system-ui;"
        "height:100%;margin:0;display:grid;place-items:center}</style>"
        "</head><body><p>Pairing display…</p>"
        f"<form id=\"f\" method=\"post\" action=\"{html.escape(action, quote=True)}\">"
        f"<input type=\"hidden\" name=\"token\" value=\"{html.escape(token, quote=True)}\">"
        "</form><script>document.getElementById('f').submit();</script>"
        "</body></html>"
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="macrosignage-kiosk",
        description=(
            "Pair a MacroSignage display and open it in Firefox kiosk mode. "
            f"Reads the display token from {TOKEN_ENV_VAR}."
        ),
    )
    parser.add_argument("display_id", type=int, help="Display ID to open.")
    parser.add_argument(
        "--server",
        default=os.environ.get(SERVER_ENV_VAR),
        help=f"MacroSignage server URL (default: ${SERVER_ENV_VAR}).",
    )
    parser.add_argument(
        "--firefox",
        help=f"Path to the Firefox binary (default: ${FIREFOX_ENV_VAR} or `firefox` on PATH).",
    )
    parser.add_argument(
        "--profile-dir",
        help=(
            "Reuse this Firefox profile dir instead of a fresh temporary one. "
            "Use a non-hidden HOME path if running snap-confined Firefox."
        ),
    )
    parser.add_argument(
        "--no-kiosk",
        action="store_true",
        help="Open in a normal window instead of kiosk mode.",
    )
    parser.add_argument(
        "--keep-profile",
        action="store_true",
        help="Do not delete the temporary profile when Firefox exits.",
    )
    return parser


def default_profile_root() -> Path:
    """Pick a profile root snap-confined Firefox can read.

    Snap Firefox's `home` interface excludes hidden paths, so $TMPDIR is unsafe.
    Use a visible directory under $HOME.
    """
    return Path.home() / ".local" / "share" / "macrosignage-kiosk"


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if not args.server:
        parser.error(f"--server is required (or set {SERVER_ENV_VAR}).")
    token = os.environ.get(TOKEN_ENV_VAR, "").strip()
    if not token:
        parser.error(f"{TOKEN_ENV_VAR} environment variable is required.")

    try:
        server = normalize_server(args.server)
        firefox_bin = find_firefox(args.firefox)
    except (ValueError, RuntimeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.profile_dir:
        profile_dir = Path(args.profile_dir)
        cleanup = False
    else:
        root = default_profile_root()
        root.mkdir(parents=True, exist_ok=True)
        profile_dir = Path(tempfile.mkdtemp(prefix=f"display-{args.display_id}-", dir=root))
        cleanup = not args.keep_profile
    profile_dir.mkdir(parents=True, exist_ok=True)

    pair_page = profile_dir / "pair.html"
    pair_page.write_text(render_pair_page(server, args.display_id, token), encoding="utf-8")
    (profile_dir / "user.js").write_text(USER_JS, encoding="utf-8")

    try:
        cmd = [firefox_bin, "--profile", str(profile_dir), "--no-remote", "--new-instance"]
        if not args.no_kiosk:
            cmd.append("--kiosk")
        cmd.append(pair_page.as_uri())
        return subprocess.call(cmd)
    finally:
        if cleanup:
            shutil.rmtree(profile_dir, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
